/*
INSERT INTO cash_card(AMOUNT) VALUES (90);
INSERT INTO cash_card(AMOUNT) VALUES (10);
INSERT INTO cash_card(AMOUNT) VALUES (20);
INSERT INTO cash_card(AMOUNT) VALUES (30);
INSERT INTO cash_card(AMOUNT) VALUES (40);
INSERT INTO cash_card(AMOUNT) VALUES (50);
INSERT INTO cash_card(AMOUNT) VALUES (60);
INSERT INTO cash_card(AMOUNT) VALUES (70);
INSERT INTO cash_card(AMOUNT) VALUES (80);
*/